name:                continuity
version:             0.1.0.0
github:              "ChrisPenner/continuity"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/continuity#readme>

dependencies:
- base >= 4.7 && < 5
- profunctors
- comonad
- lens
- mtl
- free
- async
- time

default-extensions:
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- LambdaCase
- ViewPatterns
- TypeApplications
- TypeOperators
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DerivingStrategies
- StandaloneDeriving
- TemplateHaskell
- RankNTypes

library:
  source-dirs: src

executables:
  continuity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - continuity

tests:
  continuity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - continuity
